@startuml

abstract GUIpack.templatePage {
}

class GUIpack.LoginPage {
}

class GUIpack.PatientListPage {
}

class GUIpack.PatientDetailPage {
}

GUIpack.templatePage <|-- GUIpack.LoginPage
GUIpack.templatePage <|-- PatientListPage
GUIpack.templatePage <|-- GUIpack.PatientDetailPage


@enduml